region             = "europe-west1"
zone               = "europe-west1-a"
project            = "open-source-apps-001"
cloud-run-job-name = "python-fear-greed-scraper"
application_name   = "python-fear-greed-scraper"