name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: open-source-apps-001
  IMAGE: python-fear-greed-scraper
  REGISTRY_HOSTNAME: gcr.io
  CLOUD_RUN_JOB: python-fear-greed-scraper

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.11.3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run unit tests
        run: |
          pytest
  setup-build-publish-deploy:
    needs: test
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: open-source-apps-001
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Authenticate with Container Registry
        run: |
          gcloud --quiet auth configure-docker
      # Build the Docker image
      - name: Build
        run: |-
          docker build -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:latest" .
      # Push the Docker image to Google Container Registry
      - name: Push
        run: |
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" 
          docker push "$REGISTRY_HOSTNAME"/$PROJECT_ID/"$IMAGE":latest
      - name: Deploy
        run: |
          res=$(gcloud run jobs describe $CLOUD_RUN_JOB --region=europe-west1 || echo "NOT_EXIST")
          if [ "$res" = "NOT_EXIST" ]; then
            echo "Creating Cloud Run job..."
            gcloud run jobs create ${CLOUD_RUN_JOB} --image "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" --region europe-west1 \
            --update-secrets=SENDGRID_API_KEY=python-fear-greed-sendgrid-api-key:latestMONGO_DB_CONNECTION_STRING=python-scraper-mongo-db-connection-string:latest
          else
            echo "Updating Cloud Run job..."
            gcloud run jobs update ${CLOUD_RUN_JOB} --image "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" --region europe-west1 \
            --update-secrets=SENDGRID_API_KEY=python-fear-greed-sendgrid-api-key:latest,MONGO_DB_CONNECTION_STRING=python-scraper-mongo-db-connection-string:latest
          fi
