name: Provision GCP infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:

env:
  TF_APP_WORKDIR: ./terraform

jobs:
  terraform-plan:
    name: "Terraform plan"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_APP_WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform test
        run: terraform test
      - name: Terraform Plan
        run: terraform plan -out=terraform.tfplan
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ env.TF_APP_WORKDIR }}/terraform.tfplan
          name: artifact
  terraform-apply:
    name: "Terraform apply"
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: production
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_APP_WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ${{ env.TF_APP_WORKDIR }}
      - name: Set up Cloud SDK
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve terraform.tfplan
